### ISSUE TITLE
Vague error message for "spire seq ssh," should be more specific

### ISSUE THREAD

**Issue by rsthomp** [sipb/homeworld#147]
Error message for "spire seq ssh" :

    -- verify ssh access to supervisor  (5/5) --
    Traceback (most recent call last):
    File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
    File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
    File "/usr/bin/spire/__main__.py", line 35, in <module>
    File "/usr/bin/spire/command.py", line 76, in main_invoke
    File "/usr/bin/spire/command.py", line 27, in invoke
    File "/usr/bin/spire/command.py", line 27, in invoke
    File "/usr/bin/spire/command.py", line 27, in invoke
    File "/usr/bin/spire/command.py", line 68, in invoke
    File "/usr/bin/spire/setup.py", line 35, in run_operations
    File "/usr/bin/spire/verify.py", line 90, in check_ssh_with_certs
    KeyError: 'SSH_AGENT_PID'

**Comment by celskeggs** [comment]
I've edited this issue to format the traceback properly.
