### ISSUE TITLE
Better error messages when a request is made for a token for an invalid hostname

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#176]
This is the error that I got when I wrote `grilled-cheese` instead of `grilled-cheese.mit.edu`.

```
user@hyades-admin:~/dc6-proto1$ spire infra admit grilled-cheese
[keyreq] 2017/12/28 14:05:51.251465 keyreq.go:160: while unpacking json: unexpected end of JSON input ('[{"api":"bootstrap","body":"grilled-cheese"}]' -> '')
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/spire/__main__.py", line 35, in <module>
  File "/usr/bin/spire/command.py", line 76, in main_invoke
  File "/usr/bin/spire/command.py", line 27, in invoke
  File "/usr/bin/spire/command.py", line 27, in invoke
  File "/usr/bin/spire/command.py", line 66, in invoke
  File "/usr/bin/spire/infra.py", line 8, in infra_admit
  File "/usr/bin/spire/access.py", line 53, in call_keyreq
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['keyreq', 'bootstrap-token', '/tmp/tmpy_fgcr8d/server.pem', 'egg-sandwich.mit.edu:20557', 'grilled-cheese']' returned non-zero exit status 1
```

**Comment by elefthei** [comment]
I believe in this case the error should be reported in stderr by `keyreq` since the args passed are opaque to spire (doesn't know what's a hostname and what's a FQDN).

**Comment by elefthei** [comment]
https://github.com/sipb/homeworld/pull/250
