### ISSUE TITLE
Master is broken due to depset changes

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#403]
```
ERROR: /homeworld/platform/spire/BUILD.bazel:28:1: in zip_file rule //spire:spirezip: 
Traceback (most recent call last):
	File "/homeworld/platform/spire/BUILD.bazel", line 28
		zip_file(name = 'spirezip')
	File "/homeworld/platform/bazel/zip_file.bzl", line 168, in _zip_file
		srcs += ctx.files.srcs
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
ERROR: Analysis of target '//upload:upload' failed; build aborted: Analysis of target '//spire:spirezip' failed; build aborted
```

We should get a newer version of the zip_file implementation that solves this, if one is available, or otherwise patch zip_file.bzl to be compatible with these recent changes. Also, #378 is ever-relevant.

**Comment by celskeggs** [comment]
Master is fixed. This is now just part of upgrading bazel to latest (see #404, #407).
